"""Core security and cryptographic services package.

Exports:
- SHA256Service, PerceptualHashService, HashChainService
- KeyManager, SignatureService, ManifestService
- Password, JWT, OAuth, MFA, and Rate Limiting utilities
"""

from app.core.hash_service import (
    GENESIS_HASH,
    HashChainService,
    PerceptualHashService,
    SHA256Service,
    add_block,
    calculate_bytes_hash,
    calculate_file_hash,
    compare_perceptual_hashes,
    compare_audio_fingerprints,
    compare_pdf_fingerprints,
    create_genesis_block,
    detect_tampering,
    generate_audio_fingerprint,
    generate_audio_fingerprint_dict,
    generate_image_dhash,
    generate_image_phash,
    generate_pdf_fingerprint,
    generate_video_phash,
    get_chain_state,
    verify_candidate_block,
    verify_chain,
    verify_file_hash,
)
from app.core.security import (
    blacklist_token,
    check_rate_limit,
    create_access_token,
    create_refresh_token,
    decode_token,
    exchange_code_for_tokens,
    generate_backup_codes,
    generate_secure_token,
    generate_totp_secret,
    get_google_auth_url,
    get_google_user_info,
    get_totp_uri,
    hash_password,
    increment_rate_counter,
    is_account_locked,
    is_token_blacklisted,
    record_failed_login,
    reset_failed_logins,
    reset_rate_counter,
    verify_google_id_token,
    verify_password,
    verify_token,
    verify_totp,
)
from app.core.signature_service import (
    KeyManager,
    ManifestService,
    SignatureService,
    create_manifest,
    deserialize_keys,
    deserialize_manifest,
    deserialize_private_key,
    deserialize_public_key,
    generate_ed25519_keypair,
    get_public_key,
    serialize_keys,
    serialize_manifest,
    serialize_private_key,
    serialize_public_key,
    sign_data,
    sign_manifest,
    store_keypair,
    validate_manifest,
    verify_data_signature,
    verify_signature,
)

__all__ = [
    # Classes
    "SHA256Service",
    "PerceptualHashService",
    "HashChainService",
    "KeyManager",
    "SignatureService",
    "ManifestService",
    # Hash services
    "calculate_file_hash",
    "calculate_bytes_hash",
    "verify_file_hash",
    "generate_image_phash",
    "generate_image_dhash",
    "generate_video_phash",
    "generate_audio_fingerprint",
    "generate_audio_fingerprint_dict",
    "generate_pdf_fingerprint",
    "compare_perceptual_hashes",
    "compare_audio_fingerprints",
    "compare_pdf_fingerprints",
    "GENESIS_HASH",
    "create_genesis_block",
    "add_block",
    "verify_chain",
    "verify_candidate_block",
    "get_chain_state",
    "detect_tampering",
    # Signature & Key services
    "generate_ed25519_keypair",
    "serialize_private_key",
    "serialize_public_key",
    "deserialize_private_key",
    "deserialize_public_key",
    "serialize_keys",
    "deserialize_keys",
    "store_keypair",
    "get_public_key",
    "sign_data",
    "verify_data_signature",
    "sign_manifest",
    "verify_signature",
    # Manifest services
    "create_manifest",
    "serialize_manifest",
    "deserialize_manifest",
    "validate_manifest",
    # Password & JWT services
    "hash_password",
    "verify_password",
    "generate_secure_token",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "verify_token",
    "blacklist_token",
    "is_token_blacklisted",
    # Google OAuth
    "get_google_auth_url",
    "exchange_code_for_tokens",
    "verify_google_id_token",
    "get_google_user_info",
    # MFA & Rate Limiting
    "generate_totp_secret",
    "get_totp_uri",
    "verify_totp",
    "generate_backup_codes",
    "check_rate_limit",
    "increment_rate_counter",
    "reset_rate_counter",
    "record_failed_login",
    "is_account_locked",
    "reset_failed_logins",
]
